@startuml

 hide footbox
participant ":検索画面" as seach
participant ":検索コントローラ" as control
activate seach
activate control
seach ->> control: ロングメッセージ（）
control ->> control :確認
activate control 
deactivate control
deactivate control
@enduml